/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  safelist: [
    "border-l-seal", "border-l-caution", "border-l-approve",
    "border-l-red-500", "border-l-amber-400", "border-l-green-500",
    "bg-red-500", "bg-amber-400", "bg-green-500",
  ],
  theme: {
    extend: {
      colors: {
        ink: "#0B1E3D",
        paper: "#FFFFFF",
        warm: "#F7F4EC",
        alt: "#F5F6F8",
        brand: "#E8522B",
        "brand-light": "#FEE6DB",
        "brand-dark": "#C14410",
        seal: "#C1272D",
        caution: "#D97706",
        approve: "#1E5631",
        slate2: "#5B6472",
        // shadcn variables kept for library components
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
      },
      fontSize: {
        xs: "12px",
        sm: "14px",
        base: "16px",
        lg: "20px",
        xl: "25px",
        "2xl": "31px",
        "3xl": "39px",
        "4xl": "49px",
        "5xl": "49px",
      },
      spacing: {
        3: "8px",
        5: "24px",
        10: "32px",
        14: "64px",
        20: "96px",
        28: "96px",
      },
      fontFamily: {
        display: ['"Fraunces"', "Georgia", "serif"],
        sans: ['"Inter"', "system-ui", "sans-serif"],
        mono: ['"IBM Plex Mono"', "ui-monospace", "monospace"],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "stamp-in": {
          "0%": { opacity: "0", transform: "scale(0.6) rotate(-10deg)" },
          "70%": { opacity: "1", transform: "scale(1.04) rotate(2deg)" },
          "100%": { opacity: "1", transform: "scale(1) rotate(0deg)" },
        },
        "stamp-down": {
          "0%": { transform: "scale(1) rotate(0deg)" },
          "40%": { transform: "scale(0.96) rotate(-1deg)" },
          "100%": { transform: "scale(1) rotate(0deg)" },
        },
        "fade-up": {
          "0%": { opacity: "0", transform: "translateY(18px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "stamp-in": "stamp-in 500ms cubic-bezier(.22,1.2,.36,1) both",
        "stamp-down": "stamp-down 220ms ease-in",
        "fade-up": "fade-up 0.5s ease-out both",
        "fade-in": "fade-in 0.4s ease-out both",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
