# Generated by Django 5.0.6 on 2026-07-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_hrauditlog_jobopening_loginattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobopening",
            name="experience",
            field=models.CharField(default="0–2 Years", max_length=100),
        ),
        migrations.AddField(
            model_name="jobopening",
            name="icon_name",
            field=models.CharField(
                default="default",
                help_text="Icon identifier (e.g., bde, bdm, tls, default)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="jobopening",
            name="responsibilities",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Newline-separated list of key responsibilities",
                max_length=3000,
            ),
        ),
    ]
